<a href="https://www.kaggle.com/code/taraashmittal/aimo3-dataset-creation-and-augmentation?scriptVersionId=301421303" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Dataset

We created a custom dataset of nearly 50 entries containing problems, solutions, hints, and facts needed to solve a problem (along with secondary data such as similar problems and the area of mathematics it roughly falls in). Refer to https://www.kaggle.com/datasets/taraashmittal/aimo-3 for more information.

In [1]:
!pip install -U vllm transformers accelerate sentencepiece

Collecting vllm
  Downloading vllm-0.16.0-cp38-abi3-manylinux_2_31_x86_64.whl.metadata (9.4 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Collecting transformers
  Downloading transformers-5.2.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.11.0)
Collecting accelerate
  Downloading accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (5.5.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm) (5.9.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm) (2.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm) (4.67.1)
Requirement already satisfied: blake3 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.0.8)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.1)
Collecting protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 (from vllm)
  Downloading protobuf-7.34.0-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.123.10)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.3)
Requirement already satisfied: openai>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.15.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.5)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.23.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.4.0,>=1.3.0 (from vllm)
  Downloading llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.11 (from vllm)
  Downloading outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting diskcache==5.6.3 (from vllm)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar==0.1.29 (from vllm)
  Downloading xgrammar-0.1.29-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.20.3)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Collecting msgspec (from vllm)
  Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting gguf>=0.17.0 (from vllm)
  Downloading gguf-0.18.0-py3-none-any.whl.metadata (4.5 kB)
Collecting mistral_common>=1.9.0 (from mistral_common[image]>=1.9.0->vllm)
  Downloading mistral_common-1.9.1-py3-none-any.whl.metadata (5.3 kB)
Collecting opencv-python-headless>=4.13.0 (from vllm)
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.1)
Collecting compressed-tensors==0.13.0 (from vllm)
  Downloading compressed_tensors-0.13.0-py3-none-any.whl.metadata (7.0 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.1)
Collecting watchfiles (from vllm)
  Downloading watchfiles-1.1.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from vllm) (1.13.0)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-5.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-0.84.0-py3-none-any.whl.metadata (3.0 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.13 (from vllm)
  Downloading model_hosting_container_standards-0.1.13-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.18.0)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from vllm) (1.75.1)
Collecting grpcio-reflection (from vllm)
  Downloading grpcio_reflection-1.78.0-py3-none-any.whl.metadata (1.2 kB)
Collecting numba==0.61.2 (from vllm)
  Downloading numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Requirement already satisfied: ray>=2.48.0 in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (2.53.0)
Collecting torch==2.9.1 (from vllm)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting torchaudio==2.9.1 (from vllm)
  Downloading torchaudio-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision==0.24.1 (from vllm)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Collecting flashinfer-python==0.6.3 (from vllm)
  Downloading flashinfer_python-0.6.3-py3-none-any.whl.metadata (10 kB)
Collecting loguru (from compressed-tensors==0.13.0->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.4.0)
Collecting apache-tvm-ffi!=0.1.8,!=0.1.8.post0,<0.2,>=0.1.6 (from flashinfer-python==0.6.3->vllm)
  Downloading apache_tvm_ffi-0.1.9-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.3->vllm) (8.3.1)
Collecting nvidia-cudnn-frontend>=1.13.0 (from flashinfer-python==0.6.3->vllm)
  Downloading nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting nvidia-cutlass-dsl>=4.3.4 (from flashinfer-python==0.6.3->vllm)
  Downloading nvidia_cutlass_dsl-4.4.1-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.3->vllm) (12.575.51)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.3->vllm) (26.0rc2)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.3->vllm) (0.9.0)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.2->vllm)
  Downloading llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (2025.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (9.10.2.21)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch==2.9.1->vllm)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch==2.9.1->vllm)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch==2.9.1->vllm)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (0.7.1)
Collecting nvidia-nccl-cu12==2.27.5 (from torch==2.9.1->vllm)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.3.20 (from torch==2.9.1->vllm)
  Downloading nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch==2.9.1->vllm)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch==2.9.1->vllm)
  Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.22.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.10.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.3.1)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.0.4)
Collecting fastapi-cli>=0.0.8 (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading fastapi_cli-0.0.24-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.20)
Requirement already satisfied: email-validator>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (2.3.0)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.38.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.1rc0)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.9.0->mistral_common[image]>=1.9.0->vllm) (4.25.1)
Collecting pydantic-extra-types>=2.10.5 (from pydantic-extra-types[pycountry]>=2.10.5->mistral_common>=1.9.0->mistral_common[image]>=1.9.0->vllm)
  Downloading pydantic_extra_types-2.11.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: jmespath in /usr/local/lib/python3.12/dist-packages (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm) (1.0.1)
Collecting supervisor>=4.2.0 (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm)
  Downloading supervisor-4.3.0-py2.py3-none-any.whl.metadata (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 6.5 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.4.2)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.48.0->ray[cgraph]>=2.48.0->vllm) (1.1.2)
Requirement already satisfied: cupy-cuda12x in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (13.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2026.1.4)
Collecting protobuf!=6.30.*,!=6.31.*,!=6.32.*,!=6.33.0.*,!=6.33.1.*,!=6.33.2.*,!=6.33.3.*,!=6.33.4.*,>=5.29.6 (from vllm)
  Downloading protobuf-6.33.5-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting grpcio (from vllm)
  Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (0.4.3)
Requirement already satisfied: pydantic-settings>=2.5.2 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (2.11.0)
Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (3.0.2)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm) (2.8.0)
Requirement already satisfied: typer>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.20.0)
Collecting rich-toolkit>=0.14.8 (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading rich_toolkit-0.19.7-py3-none-any.whl.metadata (1.0 kB)
Collecting fastapi-cloud-cli>=0.1.1 (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading fastapi_cloud_cli-0.14.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.9.1->vllm) (3.0.3)

In [2]:
import sqlite3
import os
import json
import pandas as pd

from vllm import LLM, SamplingParams

2026-03-04 12:56:15.754208: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772628976.043821     106 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772628976.141835     106 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772628976.957836     106 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772628976.957873     106 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772628976.957875     106 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772628976.957876     106 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

In [3]:
MODEL = "openai/gpt-oss-120b"

llm = LLM(
    model=MODEL,
    tensor_parallel_size=1,
    dtype="bfloat16",
    gpu_memory_utilization=0.95,
)

INFO 03-04 12:56:34 [utils.py:223] non-default args: {'dtype': 'bfloat16', 'gpu_memory_utilization': 0.95, 'disable_log_stats': True, 'model': 'openai/gpt-oss-120b'}

config.json: 0.00B [00:00, ?B/s]

INFO 03-04 12:56:48 [model.py:529] Resolved architecture: GptOssForCausalLM

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Parse safetensors files:   0%|          | 0/15 [00:00<?, ?it/s]

INFO 03-04 12:56:49 [model.py:1549] Using max model len 131072
INFO 03-04 12:56:50 [scheduler.py:224] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 03-04 12:56:50 [config.py:314] Overriding max cuda graph capture size to 1024 for performance.
INFO 03-04 12:56:50 [vllm.py:689] Asynchronous scheduling is enabled.

generation_config.json:   0%|          | 0.00/177 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/27.9M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/98.0 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

WARNING 03-04 12:56:52 [system_utils.py:140] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized

2026-03-04 12:56:56.044087: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772629016.061112     498 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772629016.065937     498 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772629016.078051     498 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772629016.078074     498 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772629016.078078     498 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772629016.078079     498 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

(EngineCore_DP0 pid=498) INFO 03-04 12:57:02 [core.py:97] Initializing a V1 LLM engine (v0.16.0) with config: model='openai/gpt-oss-120b', speculative_config=None, tokenizer='openai/gpt-oss-120b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=mxfp4, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='openai_gptoss', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=openai/gpt-oss-120b, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=498) INFO 03-04 12:57:02 [parallel_state.py:1234] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.19.2.2:41209 backend=nccl
(EngineCore_DP0 pid=498) INFO 03-04 12:57:02 [parallel_state.py:1445] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0

[W304 12:57:02.255039202 socket.cpp:209] [c10d] The hostname of the client socket cannot be retrieved. err=-3

(EngineCore_DP0 pid=498) INFO 03-04 12:57:03 [gpu_model_runner.py:4124] Starting to load model openai/gpt-oss-120b...
(EngineCore_DP0 pid=498) INFO 03-04 12:57:21 [cuda.py:367] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN'].
(EngineCore_DP0 pid=498) INFO 03-04 12:57:21 [mxfp4.py:160] Using Triton backend
(EngineCore_DP0 pid=498) INFO 03-04 12:59:22 [weight_utils.py:539] Time spent downloading weights for openai/gpt-oss-120b: 120.788232 seconds

Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:00<00:09,  1.51it/s]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:01<00:08,  1.49it/s]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:02<00:08,  1.43it/s]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:02<00:07,  1.44it/s]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:03<00:07,  1.40it/s]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:04<00:06,  1.42it/s]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:04<00:05,  1.39it/s]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:05<00:04,  1.41it/s]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:06<00:04,  1.39it/s]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:07<00:03,  1.41it/s]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:07<00:02,  1.39it/s]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:08<00:02,  1.40it/s]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:09<00:01,  1.43it/s]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:09<00:00,  1.40it/s]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:10<00:00,  1.43it/s]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:10<00:00,  1.42it/s]
(EngineCore_DP0 pid=498)

(EngineCore_DP0 pid=498) INFO 03-04 12:59:33 [default_loader.py:293] Loading weights took 10.65 seconds
(EngineCore_DP0 pid=498) INFO 03-04 12:59:50 [gpu_model_runner.py:4221] Model loading took 64.38 GiB memory and 166.143913 seconds
(EngineCore_DP0 pid=498) INFO 03-04 12:59:55 [backends.py:916] Using cache directory: /root/.cache/vllm/torch_compile_cache/4d787606db/rank_0_0/backbone for vLLM's torch.compile
(EngineCore_DP0 pid=498) INFO 03-04 12:59:55 [backends.py:976] Dynamo bytecode transform time: 5.00 s
(EngineCore_DP0 pid=498) INFO 03-04 13:00:03 [backends.py:351] Cache the graph of compile range (1, 16384) for later use
(EngineCore_DP0 pid=498) INFO 03-04 13:00:37 [backends.py:368] Compiling a graph for compile range (1, 16384) takes 38.11 s
(EngineCore_DP0 pid=498) INFO 03-04 13:00:37 [monitor.py:34] torch.compile takes 43.11 s in total
(EngineCore_DP0 pid=498) INFO 03-04 13:00:38 [gpu_worker.py:373] Available KV cache memory: 3.29 GiB
(EngineCore_DP0 pid=498) INFO 03-04 13:00:38 [kv_cache_utils.py:1307] GPU KV cache size: 47,904 tokens
(EngineCore_DP0 pid=498) INFO 03-04 13:00:38 [kv_cache_utils.py:1312] Maximum concurrency for 131,072 tokens per request: 0.65x

(EngineCore_DP0 pid=498) 2026-03-04 13:00:38,634 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
(EngineCore_DP0 pid=498) 2026-03-04 13:00:38,692 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 83/83 [00:58<00:00,  1.43it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 83/83 [00:09<00:00,  8.88it/s]

(EngineCore_DP0 pid=498) INFO 03-04 13:01:47 [gpu_model_runner.py:5246] Graph capturing finished in 69 secs, took 0.33 GiB
(EngineCore_DP0 pid=498) INFO 03-04 13:01:47 [core.py:278] init engine (profile, create kv cache, warmup model) took 116.92 seconds
(EngineCore_DP0 pid=498) INFO 03-04 13:01:49 [vllm.py:689] Asynchronous scheduling is enabled.
INFO 03-04 13:01:49 [llm.py:355] Supported tasks: ['generate']

In [ ]:
SYSTEM_PROMPT = """
You are a professional mathematics olympiad trainer (IMO-level).

Your job is to process one problem with its hints, solution, key ideas, facts needed, and produce:

1. A clearly rewritten Problem statement.
2. A complete, well-structured Solution.
3. Helpful Hints (progressive, from mild to strong).
4. A list of all mathematical facts needed to solve the problem.
5. Classification of all relevant mathematical areas.
6. A final machine-readable dictionary summary.

----------------------------------
FORMATTING RULES

• All mathematical expressions MUST be written in LaTeX using $...$.

• Improve clarity, grammar, and mathematical rigor wherever necessary.

• Do NOT invent facts.

• You may reorganize the solution for pedagogical quality.

----------------------------------
MATHEMATICAL AREAS (boolean classification)

Use ONLY these keys:

algebra  
induction  
polynomials  
inequalities  
geometry  
trigonometry  
limits  
differentiation  
integration  
series_products  
differential_equations  
real_analysis  
complex_analysis  
combinatorics  
enumerative_combinatorics  
probability  
pigeonhole  
linear_algebra  
determinants  
number_theory  
abstract_algebra  
group_theory  
finite_fields  
functional_equations  
generating_functions  
recurrence_relations  
game_theory  
optimisation  
invariance  
contradiction  

Each must be either true or false.

----------------------------------
OUTPUT FORMAT (MANDATORY)

Return EXACTLY one Python-style dictionary with the following keys:

problem  
solution  
hints  
facts  
algebra  
induction  
polynomials  
inequalities  
geometry  
trigonometry  
limits  
differentiation  
integration  
series_products  
differential_equations  
real_analysis  
complex_analysis  
combinatorics  
enumerative_combinatorics  
probability  
pigeonhole  
linear_algebra  
determinants  
number_theory  
abstract_algebra  
group_theory  
finite_fields  
functional_equations  
generating_functions  
recurrence_relations  
game_theory  
optimisation  
invariance  
contradiction  

Example:

{
 "problem": "A circle is divided into six consecutive sectors. Initially the numbers $1,0,1,0,0,0$ are written in the sectors in counter‑clockwise order. In one move you may choose two neighbouring sectors and increase the numbers written in both of them by $1$. Is it possible, after a finite sequence of such moves, to make all six numbers equal?",
 "solution": "Let $a_1,\\dots,a_6$ denote the numbers in the six sectors, indexed consecutively around the circle. Define the alternating sum\n$$I = a_1 - a_2 + a_3 - a_4 + a_5 - a_6.$$\nConsider one allowed move: we increase $a_i$ and $a_{i+1}$ (indices modulo $6$) by $1$. The contribution of these two terms to $I$ changes by\n\\[\\Delta I = (+1)\\cdot s_i + (+1)\\cdot s_{i+1},\\]\nwhere $s_j$ is the sign of $a_j$ in $I$ (i.e. $s_j=+1$ for odd $j$ and $s_j=-1$ for even $j$). For any $i$ the signs are opposite: $s_i = -s_{i+1}$. Hence $\\Delta I = (+1)s_i + (+1)(-s_i)=0$. Therefore $I$ is invariant under every legal move.\nInitially we have $(a_1,\\dots,a_6)=(1,0,1,0,0,0)$, so\n$$I_{\\text{initial}} = 1-0+1-0+0-0 = 2.$$\nIf after some moves all numbers become equal to a common value $k$, then\n$$I_{\\text{final}} = k - k + k - k + k - k = 0.$$\nBecause $I$ cannot change, $I_{\\text{final}}$ must equal $I_{\\text{initial}}=2$, which is impossible. Hence no sequence of allowed moves can equalise all six numbers.\nThe answer is **No**.",
 "hints": "1. Write down what a single move does to the six numbers. 2. Look for a quantity that does not change when you add $1$ to two adjacent entries. 3. An alternating sum $a_1-a_2+a_3-\\dots$ is a good candidate; check its behaviour under a move. 4. Compute this quantity for the initial configuration and for a configuration where all numbers are equal. 5. Use the invariance to reach a contradiction.",
 "facts": "1. An invariant is a quantity that remains unchanged under the allowed operations. 2. For any two consecutive indices $i$ and $i+1$, the signs in the alternating sum $a_1-a_2+a_3-\\dots$ are opposite, so adding $1$ to both entries changes the sum by $+1-1=0$. 3. If all six numbers become equal to $k$, the alternating sum equals $0$. 4. The initial alternating sum equals $2$.",
 "algebra": true,
 "induction": false,
 ...
}

----------------------------------
REASONING PROCESS (INTERNAL)

Follow these internal stages (do NOT expose them):

1. Understand problem.
2. Identify core ideas.
3. Rewrite problem.
4. Rewrite solution.
5. Produce hints.
6. Classify areas.
7. Emit dictionary.

----------------------------------
IMPORTANT

• Always interpret \\n as newline.
• Output NOTHING outside the dictionary.
• Use plain strings (no markdown).
• Do NOT output anything other that a dictionary with key and value type both strings, NOT lists 
"""

In [ ]:
data = pd.read_excel("/kaggle/input/aimo3-excel/AIMO3 Dataset.xlsx")
data.head()

In [ ]:
everything = []

def extract_and_save(text: str):
    start = text.rfind('"problem":')
    end = text.rfind('}')

    if start == -1 or end == -1 or end <= start:
        raise ValueError("Could not locate dictionary")

    chunk = "{" + text[start:end+1]

    # Remove trailing junk after final brace if any
    chunk = chunk[:chunk.rfind("}")+1]

    chunk_in_json = json.loads(chunk)

    # Parse as Python dict
    print("added", chunk_in_json)

    everything.append(chunk_in_json)

In [ ]:
def call_model(row: int) -> str:
    
    user_prompt = f"""
    Problem:
    {data["Problem"][row]}
    
    Hints:
    {data["Hints"][row]}
    
    Solution:
    {data["Solution"][row]}
    
    Key Idea:
    {data["Key Idea(s)"][row]}
    """
    
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]
    
    outputs = llm.chat(messages, sampling_params)

    return outputs[0].outputs[0].text

In [ ]:
sampling_params = SamplingParams(
    temperature=0.2,
    top_p=0.95,
    max_tokens=4096,
)

to_rerun = []

for i in range(len(data)):
    try:
        extract_and_save(call_model(i))
    except:
        to_rerun.append(i)

In [ ]:
reruns = 3

while reruns > 0:
    reruns -= 1

    to_rerun_bkp = to_rerun.copy()
    print(to_rerun_bkp)

    for i in to_rerun_bkp:  
        try:
            extract_and_save(call_model(i))
            to_rerun.remove(i)
        except:
            pass

    to_rerun_bkp = to_rerun

In [ ]:
to_rerun # some error for these? one last try:

for i in to_rerun:
    try:
        extract_and_save(call_model(i))
        to_rerun.remove(i)
    except:
        print(f"Error with {i}")

In [ ]:
df = pd.DataFrame(everything)

df.to_parquet("dataset.parquet")

conn = sqlite3.connect("dataset.sqlite")
df.to_sql("dataset", conn, if_exists="replace", index=False)
conn.close()

print("Files created:")
!ls -lh

print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

# Expanding data

We now ask the model to generate multiple variants to the same problem, expanding our dataset. We ask it to:
- Generate solution variants of the seed problem
- Give incorrect solutions and why they doesn't work
- Verify the final answer

In [4]:
data = pd.read_parquet("/kaggle/input/datasets/taraashmittal/aimo-3/dataset.parquet");
data

,problem,solution,hints,facts,algebra,induction,polynomials,inequalities,geometry,trigonometry,...,abstract_algebra,group_theory,finite_fields,functional_equations,generating_functions,recurrence_relations,game_theory,optimisation,invariance,contradiction
0,A circle is divided into six consecutive secto...,"Let $a_1,\dots,a_6$ denote the numbers in the ...",1. Write down how a single move changes the si...,1. An invariant is a quantity that remains unc...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,Let $p(x)=x^{2}-3x+2$. Prove that for every po...,First factor the divisor:\n$$p(x)=x^{2}-3x+2=(...,1. Write $p(x)$ as a product of linear factors...,1. $x^{2}-3x+2$ factors as $(x-1)(x-2)$.\n2. R...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Let $n\ge 1$ be an integer and let $\omega = e...,"Denote $P(z_1,\dots ,z_n)=\det A$. By the bin...","1. Write $\det A$ as a polynomial in $z_1,\dot...",1. Binomial theorem: $(x+y)^n=\sum_{a=0}^{n}\b...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,"Let $x_1,x_2,\dots ,x_k$ be real numbers such ...","Assume, for a contradiction, that at least one...",1. Replace each cosine by $(e^{i n\pi x}+e^{-i...,1. Euler’s formula: $\cos t = (e^{it}+e^{-it})...,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
4,Let $A$ and $B$ be $n\times n$ matrices over a...,Let $\lambda$ be an eigenvalue of $BA$ and let...,1. Recall that a matrix is nilpotent iff its o...,1. A matrix $M$ is nilpotent iff $M^{k}=0$ for...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,Let $V$ be an $n$‑dimensional vector space ove...,"Because $T^{2}=0$, for every $v\in V$ we have ...",1. Write down what the condition $T^{2}=0$ say...,1. Rank–nullity theorem: $\dim V=\dim\ker T+\o...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,Let $A$ be a real $n\times n$ matrix satisfyin...,1. **Eigenvalues are $\pm1$.**\n Let $\lambd...,1. Write down the eigenvalue equation $Av=\lam...,"1. If $Av=\lambda v$, then $A^{2}v=\lambda^{2}...",True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,Find all functions $f:\mathbb{R}\to\mathbb{R}$...,First put $x=0$ in the functional equation. We...,1. Substitute $x=0$ (or $y=0$) in the equation...,1. From $f(y)=f(0)f(y)$ we get either $f(0)=1$...,True,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
8,Find all functions $f:\mathbb{R}\to\mathbb{R}$...,Assume that a function $f$ satisfies the given...,1. Write the given relation for $x$ and then r...,1. If two equations have identical left‑hand s...,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
9,"Let $u,v\in\mathbb{R}^n$. Prove the determinan...",**Determinant.**\nFor any matrices $A\in\mathb...,1. Recall the matrix determinant lemma: for $A...,1. *Matrix determinant lemma*: $\det(I_n+AB)=\...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,Let $A$ be an $n\times n$ real matrix such tha...,Let $\lambda$ be an eigenvalue of $A$ and let ...,1. Let $\lambda$ be an eigenvalue of $A$ with ...,"1. If $Av=\lambda v$, then $A^{k}v=\lambda^{k}...",False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,Find all functions $f:\mathbb{R}\to\mathbb{R}$...,First look for a polynomial $p$ that reproduce...,1. Try a polynomial $p(x)$ and compute $p(x+y)...,1. Binomial expansion: $(x+y)^3 = x^3+3x^2y+3x...,True,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
12,Find all functions $f:\mathbb{R}_{>0}\to\mathb...,"Let $P(x,y)$ denote the assertion $xf(y)+yf(x)...","1. Write the condition as $P(x,y): xf(y)+yf(x)...","1. For any positive numbers $a,b$, the inequal...",True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,True
13,Find all continuous functions $f:\mathbb{R}\to...,First put $x=y=0$ in the functional equation. ...,1. Evaluate the equation at $x=y=0$ to find $f...,1. From $f(x+y)=f(x)f(y)$ with $x=y=0$ we get ...,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
14,"Find all pairs $(a,b)$ of positive integers su...","Let $(a,b)$ be a pair of positive integers sat...",1. Write the condition $b^2\mid a^3$ as $a^3=m...,"1. If $d\mid x$ and $d\mid y$, then $d\mid x-y...",False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15,"Let $a,b,c>0$ satisfy $abc=1$. Prove that\n\[\...","Set $x=\frac1a$, $y=\frac1b$, $z=\frac1c$. Th...",1. Replace each variable by its reciprocal: $x...,"1. Substitution $x=1/a$, $y=1/b$, $z=1/c$ tran...",False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
16,Let $p(x)$ be a non‑constant polynomial with i...,Consider the residues of $p$ modulo $n$ on the...,"1. Look at the values $p(0),p(1),\dots ,p(n-1)...",1. For any integer polynomial $p$ and any modu...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
17,Let a quadratic polynomial be written as $f(x)...,For a quadratic $f(x)=ax^2+bx+c$ define its di...,1. Look for a numerical quantity attached to a...,1. The discriminant of $ax^2+bx+c$ is $\Delta=...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,True
18,Let $(a_n)_{n\ge 1}$ be a sequence of real num...,First eliminate the absolute values by squarin...,1. From $|a_n|=|a_{n-1}+1|$ we know that $a_n$...,"1. If $x$ and $y$ are real numbers, then $|x|=...",True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
19,Let $\mathbb Z_{10}$ denote the ring of intege...,"**Part (a).**\n\n*First system* $\;4x+6y=0,\;2...",1. For each system in part (a) write the equat...,"1. $\mathbb Z_{10}=\{0,1,\dots,9\}$ with addit...",True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,Let\n$$\n f(x)=a_0+a_1x+a_2x^2+a_{10}x^{10}+a_...,Write the two polynomials as a sum of a low‑de...,1. Separate each polynomial into the part that...,"1. If $d(x)$ divides both $f(x)$ and $g(x)$, t...",True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,"For a positive integer $n$, let $\rho(n)$ deno...",First we treat the small values of $n$.\n\n* $...,1. For $n=2$ write the matrix explicitly and c...,1. A matrix has full rank $n$ iff its determin...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,Let $1\le a_1<a_2<\dots<a_{\ell}\le n$ be inte...,**Even $n$ – a counterexample.**\nLet $n=2k$ b...,1. Test the claim for small even values of $n$...,1. **Pigeonhole principle** – if the union of ...,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
23,Let $x_0\in\mathbb{R}$ and define a sequence $...,(a) From the recurrence we have\n\[ x_{n+1}-x_...,1. (a) Write the recurrence for the difference...,1. A linear recurrence $x_{n}=\frac{x_{n-1}+c}...,True,False,True,False,False,False,...,False,False,False,True,False,True,False,False,True,False
24,Let $f:\mathbb{R}\to\mathbb{R}$ be a continuou...,"Denote $I= f(\mathbb{R})$, the image of $f$. B...",1. Apply the functional equation to the known ...,1. The image of a continuous function $\mathbb...,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
25,Let\n$$p(x)=a_0+a_1x+\dots +a_nx^n$$\nbe a pol...,"Because $p(s)=0$, the factor theorem gives\n$$...","1. Use the factor theorem: since $p(s)=0$, wri...",1. Factor theorem: if $p(s)=0$ then $p(x)=(x-s...,True,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
26,Let $m$ be a positive integer. Prove that ther...,**Existence.** Consider a scalar matrix $A=\l...,1. Try a matrix that is a scalar multiple of t...,1. The cubic polynomial $p(x)=x^{3}-x-1$ has d...,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,"A frog starts at the point $(0,0)$ on the inte...",First list all integer vectors of length $10$....,1. Determine every integer vector whose length...,1. Integer solutions of $a^2+b^2=100$ are $(\p...,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,True,True
28,Let $(s_n)$ be a sequence of real numbers and ...,From $t_{k+1}-t_k=1$ we see that $(t_k)$ is an...,1. From $t_{k+1}-t_k=1$ deduce that $(t_k)$ is...,1. If the first differences of a sequence sati...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,Let $L=\mathbb{Z}^2$ be the integer lattice.\n...,(a) Suppose a regular hexagon $A_0A_1\dots A_5...,1. Write the squared distance between two latt...,1. The squared Euclidean distance between $(x_...,True,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
30,"Find all triples of positive integers $(a,b,c)...",We look for all positive integer solutions of\...,1. Because the equation is symmetric you may a...,"1. If $x,y,z>0$ then $x^3+y^3+z^3\le3\max\{x,y...",True,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,True
31,"Let $a,b,c$ be real numbers greater than $1$ s...",Let $k$ denote the common value of the three p...,1. The three equations are symmetric; you may ...,"1. For real numbers $x\le y$, the floor functi...",True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
32,A positive integer is called *fantabulous* if ...,Define a relation $a\leftrightarrow b$ to mean...,1. Translate the given condition into a relati...,"1. The hypothesis “if any element of $\{m,2m+1...",False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,Find all functions $f:\mathbb{Z}_{\ge 0}\to\ma...,Assume that a function $f$ satisfying the thre...,1. Substitute $n=0$ (or $m=0$) in the function...,1. Substituting $n=0$ in $f(m)f(n)=f(m+n)+f(|m...,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
34,"Find all real numbers $x\in[0,2\pi]$ such that...",Let\n$$S=\sum_{k=1}^{n}e^{ikx}=\sum_{k=1}^{n}(...,1. Write the two sums as the real and imaginar...,1. Euler's formula: $e^{i\theta}=\cos\theta+i\...,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
35,"Find all pairs $(p,n)$ where $p$ is a prime nu...",We distinguish two cases.\n\n**1. $p$ odd.**\n...,1. From $p^{n}+1\mid n^{p}+1$ obtain the inequ...,1. If $a\mid b$ then $a\le b$ for positive int...,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
36,Let $f(n)$ denote the number of integer partit...,**Generating function.**\nA part $k$ is allowe...,1. Write the generating function as a product ...,1. Euler’s product for partitions: $\sum_{n\ge...,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
37,Find all functions $f:\mathbb{Z}_{\ge 0}\times...,**Step 1 – Uniqueness.**\nThe recurrence (ii) ...,"1. Compute the first few values of $f(m,n)$ us...",1. The Delannoy numbers count lattice paths fr...,True,True,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
38,"For a real parameter $a$, define\n$$F_a(x)=\su...","Write $x=1-\delta$ with $\delta\in(0,1)$ and $...",1. Rewrite the term $n^{a}e^{-n x^{2}}x^{n}$ u...,"1. For $0<x<1$, $x^{n}=e^{n\ln x}$ and $\ln(1-...",False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,"Let $a_1,a_2,\dots ,a_n$ be positive integers ...",For any positive real numbers $a$ and $b$ we h...,1. Start with the elementary inequality $(a-b)...,"1. For any real numbers $a,b>0$, $(a-b)^2\ge 0...",True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
40,nan,Consider constant polynomials separately.,nan,,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,,,,,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42,Let $A=(a_{ij})$ be the $n\times n$ matrix def...,"Set \(\omega=e^{2\pi i/n}\). For each $k=0,1,\...",1. Observe that $A$ permutes the standard basi...,1. The $n\times n$ cyclic shift matrix $A$ sat...,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,Let $(F_n)_{n\ge 1}$ be the Fibonacci sequence...,We use the classic combinatorial interpretatio...,1. Recall that $F_m$ counts tilings of a board...,1. $F_m$ equals the number of tilings of a boa...,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
44,Let $A$ be a real $n\times n$ matrix satisfyin...,"Because $A^{2}=I_{n}$, the minimal polynomial ...",1. Write down the polynomial satisfied by $A$ ...,1. If a matrix $A$ satisfies a polynomial $p(A...,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
45,Find all ordered pairs of positive integers $(...,Because the two expressions are obtained from ...,1. Notice that swapping $a$ and $b$ exchanges ...,"1. If $\frac{p}{q}$ is an integer, then $q\mid...",True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
46,"Let\n$$p_n(x)=x^n+x^{n-1}+\dots +x-k,$$\nwhere...",(a) For $x>0$ the derivative\n$$p_n'(x)=n x^{n...,1. Compute $p_n'(x)$ and check its sign for $x...,"1. For $x>0$, $p_n'(x)=n x^{n-1}+\dots+1>0$, s...",True,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
47,Let $(a_n)_{n\ge 1}$ be a sequence of non‑nega...,"Define $b_n\in\{0,1\}$ by $a_{n+1}=2S_n+b_n$. ...",1. Write the recurrence in terms of the partia...,"1. If $x_{n+1}=c\,x_n+d_n$ with $c>1$ and $d_n...",True,True,True,True,False,False,...,False,False,False,False,False,True,False,False,False,True
48,Determine all positive integers $n$ for which ...,"Write $\omega=e^{2\pi i/n}$, the primitive $n$...",1. Rewrite the two real equations as a single ...,1. $\omega=e^{2\pi i/n}$ is a primitive $n$‑th...,True,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,True
49,Find the unique formal power series $F(x)=x+a_...,Write $F(x)=\sum_{n\ge 1}a_nx^n$ with $a_1=1$....,1. Set $x=0$ in the functional equation to see...,1. The geometric series $\frac{1}{1-x}=\sum_{k...,True,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
50,Find all real polynomials $P\in\mathbb{R}[x]$ ...,Let $P$ be a polynomial satisfying the identit...,1. Substitute $y=0$ to obtain a relation invol...,"1. For any polynomial $Q$, $\deg(Q(x+y))$ (vie...",True,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
51,Let $k\ge 2$ be an integer. Determine all infi...,First observe that $P(n+1)/P(n)=a_{n+2}/a_n$ f...,1. Write the relation $P(n+1)/P(n)=a_{n+2}/a_n...,1. For a polynomial $P$ of degree $k$ with lea...,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
52,Let the set of all integers \(\mathbb Z\) be w...,For an arithmetic progression \(P_i=\{a_i+kd_i...,1. For a progression with difference \(d\) cou...,1. An arithmetic progression \(\{a+kd\mid k\in...,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
53,Find all functions $f:\mathbb{R}\to\mathbb{R}$...,"Let $P(x,y)$ denote the assertion $f(x^{2}+f(y...","1. Write $P(x,y)$ for the given assertion and ...","1. From $P(0,y)$ we get $f(f(y))=y+f(0)^{2}$. ...",True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
54,Let $A$ be a $3\times3$ real matrix satisfying...,From the given relation we move all terms to o...,1. Write the given equation as $A^{3}-A^{2}-A=...,"1. If a square matrix $A$ satisfies $AB=I$, th...",True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [5]:
SYSTEM_PROMPT = '''
You are a world-class IMO-level mathematician, problem designer, and mathematical critic.

Your task is to generate multiple deeply distinct solution variants AND several plausible but incorrect solution attempts for a single mathematics olympiad problem.

The goal is to maximize reasoning diversity, include adversarial robustness, and preserve the SAME final answer for all correct variants.

---

INPUT

You will receive a Python-style dictionary with:

problem
solution
hints
facts
tags

---

STEP 1 — STRATEGY ANALYSIS (internal)

Internally determine:

• The core strategy of the provided solution.
• Its strategy class (e.g., invariant, extremal principle, contradiction, symmetry, coordinate geometry, algebraic manipulation, counting, etc.).

You MUST avoid reusing the same core idea in at least 3 correct variants.

---

STEP 2 — CORRECT VARIANT GENERATION

Generate as many as possible correct solution variants.

Requirements:

• All variants must solve the SAME problem.
• All must reach the SAME final numerical answer.
• At least 3 variants must use a fundamentally different core strategy.
• At least 2 variants must significantly reorganize logical flow.
• At least 1 variant must be more computational.
• At least 1 variant must be more structural or synthetic.
• Each solution must be rigorous and logically complete.
• Each solution must include an explicit verification section.
• End with \boxed{INTEGER} whenever possible.

---

STEP 3 — PLAUSIBLE BUT INCORRECT SOLUTIONS

Generate incorrect but highly plausible solution attempts.

Each incorrect solution must:

• Follow a realistic reasoning path.
• Contain a subtle but nontrivial logical, algebraic, or conceptual error.
• Clearly identify the precise step where the reasoning fails.
• Provide a short explanation of why that step is invalid.
• NOT accidentally reach the correct final answer.

Errors may include:

• Misapplied theorem.
• Invalid algebraic manipulation.
• Incorrect assumption of symmetry.
• Hidden division by zero.
• Overlooked constraint.
• False generalization.

---

ANTI-COLLAPSE RULES

• Do NOT paraphrase the original solution.
• Do NOT reuse the same central lemma in more than 2 correct variants.
• Vary the main insight.
• Vary ordering of deductions.
• Vary abstraction level and structural emphasis.
• Incorrect solutions must differ meaningfully from each other.

---

MATHEMATICAL REQUIREMENTS

• All mathematics must use LaTeX with $...$.
• Logical steps must be explicit.
• No handwaving.
• Every claim must follow from previous statements.

---

OUTPUT FORMAT (MANDATORY)

Return EXACTLY one valid JSON object.

All backslashes must be escaped as double backslashes (\\).
The output must be valid strict JSON.

Keys MUST be of form:

correct_variant_1
correct_variant_2
correct_variant_3
correct_variant_4
correct_variant_5
...
incorrect_variant_1
incorrect_variant_2
...

For example:

"correct_variant_1": {
 "problem": "A circle is divided into six consecutive sectors. Initially the numbers $1,0,1,0,0,0$ are written in the sectors in counter‑clockwise order. In one move you may choose two neighbouring sectors and increase the numbers written in both of them by $1$. Is it possible, after a finite sequence of such moves, to make all six numbers equal?",
 "solution": "Let $a_1,\\dots,a_6$ denote the numbers in the six sectors, indexed consecutively around the circle. Define the alternating sum\n$$I = a_1 - a_2 + a_3 - a_4 + a_5 - a_6.$$\nConsider one allowed move: we increase $a_i$ and $a_{i+1}$ (indices modulo $6$) by $1$. The contribution of these two terms to $I$ changes by\n\\[\\Delta I = (+1)\\cdot s_i + (+1)\\cdot s_{i+1},\\]\nwhere $s_j$ is the sign of $a_j$ in $I$ (i.e. $s_j=+1$ for odd $j$ and $s_j=-1$ for even $j$). For any $i$ the signs are opposite: $s_i = -s_{i+1}$. Hence $\\Delta I = (+1)s_i + (+1)(-s_i)=0$. Therefore $I$ is invariant under every legal move.\nInitially we have $(a_1,\\dots,a_6)=(1,0,1,0,0,0)$, so\n$$I_{\\text{initial}} = 1-0+1-0+0-0 = 2.$$\nIf after some moves all numbers become equal to a common value $k$, then\n$$I_{\\text{final}} = k - k + k - k + k - k = 0.$$\nBecause $I$ cannot change, $I_{\\text{final}}$ must equal $I_{\\text{initial}}=2$, which is impossible. Hence no sequence of allowed moves can equalise all six numbers.\nThe answer is **No**.",
 "hints": "1. Write down what a single move does to the six numbers. 2. Look for a quantity that does not change when you add $1$ to two adjacent entries. 3. An alternating sum $a_1-a_2+a_3-\\dots$ is a good candidate; check its behaviour under a move. 4. Compute this quantity for the initial configuration and for a configuration where all numbers are equal. 5. Use the invariance to reach a contradiction.",
 "facts": "1. An invariant is a quantity that remains unchanged under the allowed operations. 2. For any two consecutive indices $i$ and $i+1$, the signs in the alternating sum $a_1-a_2+a_3-\\dots$ are opposite, so adding $1$ to both entries changes the sum by $+1-1=0$. 3. If all six numbers become equal to $k$, the alternating sum equals $0$. 4. The initial alternating sum equals $2$.",
},
"correct_variant_2": {
 "problem": ...
 "solution": ...
 ...
}

Structure of EACH CORRECT variant string must be:

"problem": <list the problem>
"solution": <complete reasoning>
"hints": <how somebody else might approach and attack the problem using the technique you're using>  
"facts": <strategy and main insights/observations>
"verification": <explicit verification>
"answer": \boxed{INTEGER}

Structure of EACH INCORRECT variant string must be:

"attempt": <plausible reasoning>
"failure": <exact step where error occurs>
"explanation": <clear explanation>

---

CRITICAL OUTPUT RULES

• Interpret \n as newline.
• Output NOTHING outside the dictionary.
• Do NOT include backticks.
• Do NOT include markdown.
'''

In [6]:
tags = ["algebra", "induction", "polynomials", "inequalities", "geometry", "trigonometry", "limits", "differentiation", "integration", "series_products", "differential_equations", "real_analysis", "complex_analysis", "combinatorics", "enumerative_combinatorics", "probability", "pigeonhole", "linear_algebra", "determinants", "number_theory", "abstract_algebra", "group_theory", "finite_fields", "functional_equations", "generating_functions", "recurrence_relations", "game_theory", "optimisation", "invariance", "contradiction"]

everything = []

def generate_data(row: int):
    p_tags = data[tags].apply(lambda row: row.index[row].tolist(),axis=1)[row]
    
    user_prompt = f"""
    Problem:
    {data["problem"][row]}
    
    Hints:
    {data["hints"][row]}
    
    Solution:
    {data["solution"][row]}
    
    Key Idea:
    {data["facts"][row]}

    Tags:
    {p_tags}
    """
    
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]

    outputs = llm.chat(messages, sampling_params)
    raw_answer = outputs[0].outputs[0].text

    x = json.loads(r"{"+raw_answer[raw_answer.index('"correct_variant_1":'):])
    x['tags'] = p_tags

    everything.append(x)

In [7]:
sampling_params = SamplingParams(
    temperature=0.95,
    top_p=0.9,
    max_tokens=4096*2,
)

everything.clear()
to_rerun = []

for i in range(len(data)):
    try:
        generate_data(i)
    except:
        print(f"Error: Row {i}")
        to_rerun.append(i)

INFO 03-04 13:08:19 [hf.py:318] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 1

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 2

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 3

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 13

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 15

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 18

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 19

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 21

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 23

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 25

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 26

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 30

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 36

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 41

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 42

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 46

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 48

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 50

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 51

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 53

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 54

In [11]:
attempts = 0

for i in to_rerun:
    try:
        generate_data(i)
    except:
        print(f"Error: Row {i}")
        to_rerun.append(i)
        attempts += 1

    if attempts > 20:
        break

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 1

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 19

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 23

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 25

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 41

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 46

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 51

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 19

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 23

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 19

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 23

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 19

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Error: Row 23

In [13]:
to_rerun # looks like 19 and 23 are lost, ok

[1,
 2,
 13,
 19,
 21,
 23,
 25,
 41,
 46,
 51,
 54,
 1,
 19,
 23,
 25,
 41,
 46,
 51,
 19,
 23,
 19,
 23,
 19,
 23]

In [14]:
with open("backup_data.txt", "w") as f:
    f.write(str(everything))

In [16]:
correct_solutions = pd.DataFrame()

for i in range(len(everything)):
    for j in everything[i].keys():
        if j.startswith("correct"):
            everything[i][j]['tags'] = [everything[i]['tags']]
            correct_solutions = pd.concat([correct_solutions, pd.DataFrame(everything[i][j], index=[0])], ignore_index=True)

correct_solutions

,problem,solution,hints,facts,verification,answer,tags
0,A circle is divided into six consecutive secto...,"Let $a_1,\dots ,a_6$ be the numbers in the sec...",1. Write the effect of a move on the six varia...,The alternating sum $I$ is an invariant becaus...,We verified that for each of the six possible ...,\boxed{0},"[algebra, invariance, contradiction]"
1,A circle is divided into six consecutive secto...,Colour the sectors alternately black and white...,1. Assign two colours alternating around the c...,The quantity $D$ is invariant since every move...,Checking each of the six possible neighbour pa...,\boxed{0},"[algebra, invariance, contradiction]"
2,A circle is divided into six consecutive secto...,Work modulo $2$. Let $b_i = a_i \pmod 2$. A ...,1. Look at the problem modulo $2$; a move flip...,Flipping two bits leaves the xor of all bits u...,We verified that each legal move toggles exact...,\boxed{0},"[algebra, invariance, contradiction]"
3,A circle is divided into six consecutive secto...,We treat each move as adding one of the six ve...,1. Translate each move into a vector addition....,"The orthogonal vector $(1,-1,1,-1,1,-1)$ yield...","Checking $\langle v_i,(1,-1,1,-1,1,-1)\rangle ...",\boxed{0},"[algebra, invariance, contradiction]"
4,A circle is divided into six consecutive secto...,Introduce the generating function $F(x)=a_1 + ...,1. Encode the six numbers as coefficients of a...,Evaluation at $x=-1$ annihilates every move po...,We verified $\phi(x^{i}+x^{i+1})=0$ for all $i...,\boxed{0},"[algebra, invariance, contradiction]"
...,...,...,...,...,...,...,...
254,"Let\n$$p_n(x)=x^n+x^{n-1}+\dots +x-k,$$\nwhere...",### (a) Computational proof using Newton's met...,1. Use Newton's method to see that the zero is...,1. $p_n'(x)=\sum_{i=0}^{n-1}(i+1)x^{i}>0$ for ...,All computational steps are justified; the lim...,\boxed{\frac{k}{k+1}},"[algebra, polynomials, inequalities, limits, d..."
255,Let $k\ge 2$ be an integer. Determine all infi...,**Step 1 – asymptotics and parity of $k$.**\nW...,1. Turn the identity $P(n)=a_n a_{n+1}$ into a...,"1. For a degree $k$ polynomial $P$, $P(n+1)/P(...",Take any $Q(x)=x^{m}+1$. Then $a_n=Q(n)=n^{m}+...,"No solution for odd $k$. For even $k=2m$, the ...","[algebra, induction, polynomials, limits, cont..."
256,Let $k\ge 2$ be an integer. Determine all infi...,### 1. A factorisation viewpoint\nFor each $n...,"1. Look at $\gcd(P(x),P(x-1))$; its values at ...","1. $\gcd(P(x),P(x-1))$ evaluated at $x=n$ equa...",Take $Q(x)=2x+3$. Then $a_n=2n+3>0$ for all $n...,"Even $k$: $a_n=Q(n)$ with $Q\in\mathbb Z[x]$, ...","[algebra, induction, polynomials, limits, cont..."
257,Let $k\ge 2$ be an integer. Determine all infi...,#### 1. Ratio method without series expansion...,1. Derive the ratio $a_{n+2}/a_n$ from $P$.\n2...,1. $\frac{P(n+1)}{P(n)}=1+\frac{k}{n}+O(1/n^{2...,Choose $Q(x)=x^{2}+1$ (degree $m=2$). Then $a_...,"Even $k$: $a_n=Q(n)$ with $Q\in\mathbb Z[x]$, ...","[algebra, induction, polynomials, limits, cont..."
258,Let $k\ge 2$ be an integer. Determine all infi...,#### 1. Direct use of integer‑valued polynomi...,"1. Consider $\gcd(P(x),P(x-1))$; its values at...",1. An integer‑valued polynomial can be express...,Take $Q(x)=3\binom{x}{2}+2\binom{x}{1}+1=\frac...,"Even $k$: $a_n=Q(n)$ with $Q\in\mathbb Z[x]$, ...","[algebra, induction, polynomials, limits, cont..."

In [17]:
correct_solutions.to_parquet("correct_solutions.parquet")

In [21]:
everything[1].keys()

dict_keys(['correct_variant_1', 'correct_variant_2', 'correct_variant_3', 'correct_variant_4', 'correct_variant_5', 'incorrect_variant_1', 'incorrect_variant_2', 'incorrect_variant_3', 'tags'])

In [22]:
incorrect_solutions = pd.DataFrame()

for i in range(len(everything)):
    for j in everything[i].keys():
        if j.startswith("incorrect"):
            everything[i][j]['problem'] = everything[i]['correct_variant_1']['problem']
            incorrect_solutions = pd.concat([incorrect_solutions, pd.DataFrame(everything[i][j], index=[0])], ignore_index=True)

incorrect_solutions

,attempt,failure,explanation,problem
0,Define the alternating sum $I = a_1 - a_2 + a_...,The step where the change of $I$ for the move ...,In the alternating sum the coefficients of $a_...,A circle is divided into six consecutive secto...
1,Observe that each move adds $2$ to the total s...,The conclusion that reaching $k=1$ is possible...,While the parity of the total sum is indeed pr...,A circle is divided into six consecutive secto...
2,"Since $AB$ is nilpotent, its minimal polynomia...",The claim that the minimal polynomial of $AB$ ...,Minimal polynomials are not ordered by the pro...,Let $A$ and $B$ be $n\times n$ matrices over a...
3,"If $(AB)^{k}=0$, then multiplying on the left ...",The equality $B(AB)^{k}A=(BA)^{k+1}$ is incorr...,"Without commutativity, $B(AB)^{k}A$ expands to...",Let $A$ and $B$ be $n\times n$ matrices over a...
4,"Because $AB$ is nilpotent, $\det(AB)=0$. Dete...",The inference that a singular matrix must be n...,A matrix can be singular (non‑invertible) with...,Let $A$ and $B$ be $n\times n$ matrices over a...
...,...,...,...,...
120,"Use generating functions: $A(x)=\frac1{1-x}$, ...",The error occurs when reading off the coeffici...,The series was truncated too early; the coeffi...,"Determine the number of ordered triples $(a,b,..."
121,From $p_n(x)=x^n+\dots +x-k=0$ we can factor $...,"The step “as $n\to\infty$, the left‑hand side ...",The infinite‑geometric‑series formula is valid...,"Let\n$$p_n(x)=x^n+x^{n-1}+\dots +x-k,$$\nwhere..."
122,"Observe that $p_n'(x)=n x^{n-1}+\dots +1>0$, s...",The equality $a_{n+1}=a_n+ a_n^{n+1}$ is false...,One cannot substitute $a_n$ for $a_{n+1}$ insi...,"Let\n$$p_n(x)=x^n+x^{n-1}+\dots +x-k,$$\nwhere..."
123,From $P(n)=a_n a_{n+1}$ we get $a_{n+1}=P(n)/a...,The step where the recurrence $a_{n+2}=a_n+ k ...,Dividing $P(n)=a_n a_{n+1}$ by $a_n$ gives $a_...,Let $k\ge 2$ be an integer. Determine all infi...
124,"Assume $k$ is even, $k=2m$. Let $a_n=n^{m}+(-1...",The equality $P(n)=a_n a_{n+1}$ fails because ...,Computing $a_n a_{n+1}$ gives $n^{2m}+(-1)^{n}...,Let $k\ge 2$ be an integer. Determine all infi...

In [25]:
incorrect_solutions.to_parquet("incorrect_solutions.parquet")